//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_13.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework_13.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacob 29195
        ///Michael 26991
        ///Joshua 24950
        ///Matthew 23706
        ///Andrew 21852
        ///Joseph 21265
        ///Ethan 21206
        ///Daniel 20947
        ///Christopher 20781
        ///Anthony 19990
        ///William 19853
        ///Ryan 19478
        ///Nicholas 19457
        ///David 18440
        ///Tyler 17989
        ///Alexander 17800
        ///John 17198
        ///James 16665
        ///Dylan 15649
        ///Zachary 15341
        ///Brandon 15071
        ///Jonathan 14954
        ///Samuel 14523
        ///Christian 14022
        ///Benjamin 13948
        ///Justin 13639
        ///Nathan 13497
        ///Jose 13082
        ///Logan 13065
        ///Gabriel 12806
        ///Kevin 12031
        ///Noah 11700
        ///Austin 11553
        ///Caleb 11513
        ///Robert 11234
        ///Thomas 10879
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string boynames {
            get {
                return ResourceManager.GetString("boynames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emily 25494
        ///Emma 22532
        ///Madison 19986
        ///Hannah 17393
        ///Olivia 15982
        ///Abigail 15789
        ///Alexis 14659
        ///Ashley 14402
        ///Elizabeth 13927
        ///Samantha 13733
        ///Isabella 13635
        ///Sarah 13602
        ///Grace 12659
        ///Alyssa 12618
        ///Lauren 10955
        ///Kayla 10823
        ///Brianna 10445
        ///Jessica 10371
        ///Taylor 10200
        ///Sophia 9665
        ///Anna 9382
        ///Victoria 9226
        ///Natalie 9105
        ///Chloe 9012
        ///Sydney 8815
        ///Hailey 8682
        ///Jasmine 7959
        ///Rachel 7888
        ///Morgan 7851
        ///Megan 7743
        ///Jennifer 7503
        ///Kaitlyn 7486
        ///Julia 7394
        ///Haley 7110
        ///Mia 7059
        ///Katherine 7056
        ///Destiny 6859
        ///Alexa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string girlnames {
            get {
                return ResourceManager.GetString("girlnames", resourceCulture);
            }
        }
    }
}
